2024-11-06 15:02:09.058 | INFO     | __main__:main:73 - 正在初始化机器人...
2024-11-06 15:02:09.060 | INFO     | src.robot.flexiv:__init__:20 - 正在连接Flexiv机器人 192.168.2.110...
2024-11-06 15:02:09.663 | INFO     | src.robot.flexiv:__init__:24 - 正在使能机器人...
2024-11-06 15:02:09.689 | INFO     | src.robot.flexiv:__init__:26 - 机器人初始化完成
2024-11-06 15:02:09.689 | INFO     | __main__:main:80 - 正在初始化相机...
2024-11-06 15:02:10.445 | INFO     | __main__:main:87 - 正在初始化标记检测器...
2024-11-06 15:02:10.451 | INFO     | __main__:main:94 - 正在初始化手眼标定器...
2024-11-06 15:02:10.456 | ERROR    | __main__:main:125 - 程序运行出错: Error locating target 'src.calibration.hand_eye_calibrator.HandEyeCalibrator', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: calibration
2024-11-06 15:02:10.457 | ERROR    | __main__:main:127 - Traceback (most recent call last):
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 970, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'src.calibration.hand_eye_calibrator.HandEyeCalibrator'; 'src.calibration.hand_eye_calibrator' is not a package

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'src.calibration.hand_eye_calibrator.HandEyeCalibrator':
ModuleNotFoundError("No module named 'src.calibration.hand_eye_calibrator.HandEyeCalibrator'; 'src.calibration.hand_eye_calibrator' is not a package")
Are you sure that 'HandEyeCalibrator' is importable from module 'src.calibration.hand_eye_calibrator'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yutong/OptiCalibrate/main.py", line 95, in main
    calibrator = instantiate(cfg.calibration)
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.calibration.hand_eye_calibrator.HandEyeCalibrator', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: calibration

2024-11-06 15:02:10.473 | INFO     | __main__:main:131 - 程序已终止
2024-11-06 15:02:10.474 | INFO     | src.robot.flexiv:__del__:53 - 正在关闭机器人连接...
2024-11-06 15:02:10.474 | ERROR    | src.robot.flexiv:__del__:56 - 关闭机器人失败: 'flexivrdk.Robot' object has no attribute 'disable'
