2024-11-06 15:47:48.267 | INFO     | __main__:async_main:14 - 正在初始化机器人...
2024-11-06 15:47:48.270 | INFO     | src.robot.flexiv:__init__:22 - 正在连接Flexiv机器人 192.168.2.110...
2024-11-06 15:47:48.873 | INFO     | src.robot.flexiv:__init__:26 - 正在使能机器人...
2024-11-06 15:47:48.898 | INFO     | src.robot.flexiv:__init__:28 - 机器人初始化完成
2024-11-06 15:47:48.899 | INFO     | __main__:async_main:21 - 正在初始化相机...
2024-11-06 15:47:49.567 | INFO     | __main__:async_main:28 - 正在初始化标记检测器...
2024-11-06 15:47:49.571 | INFO     | __main__:async_main:35 - 正在初始化手眼标定器...
2024-11-06 15:47:49.580 | INFO     | src.calibration.hand_eye_calibrator:__init__:65 - 手眼标定器初始化完成，使用eye_in_hand方法
2024-11-06 15:47:49.580 | INFO     | __main__:async_main:41 - 系统初始化完成
2024-11-06 15:47:49.580 | INFO     | __main__:async_main:42 - 按 's' 键保存当前姿态，按 'ESC' 键结束采集
2024-11-06 15:47:49.580 | ERROR    | __main__:async_main:74 - 程序运行出错: Key 'collector' is not in struct
    full_key: collector
    object_type=dict
2024-11-06 15:47:49.581 | ERROR    | __main__:async_main:76 - Traceback (most recent call last):
  File "/home/yutong/OptiCalibrate/main.py", line 49, in async_main
    **cfg.collector  # 从配置文件中读取采集器配置
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 359, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 475, in _get_node
    self._validate_get(key)
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/yutong/anaconda3/envs/robocal/lib/python3.8/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
omegaconf.errors.ConfigAttributeError: Key 'collector' is not in struct
    full_key: collector
    object_type=dict

2024-11-06 15:47:49.595 | INFO     | __main__:async_main:80 - 程序已终止
